schema_version: 1

context:
  name: freeze-core
  version: "0.7.6"
  sha256: 2f6d885205e3aa36854f414841380b6ee7cf8eda6733a4e141e34c4575890039

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace("-", "_") }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip: match(python, "<3.11")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  dynamic_linking:
    missing_dso_allowlist:
      - if: win
        then:
          - "**/cx_Logging.*.pyd"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools ==84.0
    - if: win
      then:
        - cx_logging >=3.2
  run:
    - python
    - filelock >=3.20.3
    - if: win
      then:
        - cabarchive >=0.2.4
        - striprtf >=0.0.26

tests:
  - python:
      imports:
        - freeze_core
  - files:
      source:
        - pyproject.toml
        - tests
    requirements:
      run:
        - coverage >=7.13.0
        - pytest >=9.0.3
        - if: not win
          then:
            - cabarchive >=0.2.4
            - striprtf >=0.0.26
    script:
      - coverage run -m pytest tests -k "not venv"

about:
  license: MIT
  license_file: LICENSE
  summary: Core dependency for cx_Freeze.
  repository: https://github.com/marcelotduarte/freeze-core
  homepage: https://marcelotduarte.github.io/cx_Freeze
  documentation: https://cx-freeze.readthedocs.io/

extra:
  recipe-maintainers:
    - marcelotduarte
